galaxy_info:
  author: Andreas Dolp
  description: Installiert einen apt-cacher-ng auf einem Debian host.
  company: ausecus GmbH
  license: propriet√§s
  min_ansible_version: 2.9
  platforms:
  - name: Debian
    versions:
    - buster
  galaxy_tags: []
dependencies: []
