---
galaxy_info:
  author: Andreas Dolp
  description: Role to set SSH server settings
  company:
  license: license (MIT)

  min_ansible_version: 2.9

  platforms:
  - name: Debian
    versions:
    - buster
  - name: Ubuntu
    versions:
    - focal

  galaxy_tags:
    - common

  dependencies:
