---
- name: Set timezone to Europe/Berlin.
  community.general.timezone: name=Europe/Berlin

- name: Install NTP package
  apt:
    name: ntp
    state: present
- name: Copy the ntp.conf template file, notify handler restart ntp
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify: restart ntp
- name: Ensure ntp is started an enabled on restart.
  service:
    name: ntp
    state: started
    enabled: yes
